<a href="https://colab.research.google.com/github/chaiyawat19/DataScinceLab/blob/main/%E0%B8%82%E0%B9%89%E0%B8%AD_LAB07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np # linear algebra
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
enroll=pd.read_excel('/content/drive/MyDrive/LabDataScince/enrollement.xlsx')
enroll.head(20)

,STUDENTCODE,COURSECODE,COURSENAME,GRADE
0,6xx2xxx-8,342117,การเขียนโปรแกรมเชิงโครงสร้างสำหรับเทคโนโลยีสาร...,4.0
1,6xx2xxx-8,342181,ตรรกะและแนวคิด,2.5
2,6xx2xxx-8,342182,ความบันดาลใจในวิชาชีพเทคโนโลยีสารสนเทศ,2.5
3,6xx2xxx-8,GE141166,ศาสตร์ของความสุข,4.0
4,6xx2xxx-8,GE151144,พหุวัฒนธรรม,2.5
5,6xx2xxx-8,GE321415,ทักษะการเรียนรู้,3.5
6,6xx2xxx-8,LI101001,ภาษาอังกฤษ 1,3.0
7,6xx2xxx-8,300109,วิทยาศาสตร์กายภาพ,2.5
8,6xx2xxx-8,314106,คณิตศาสตร์ทั่วไป,2.0
9,6xx2xxx-8,342118,แนวคิดและการเขียนโปรแกรมเชิงวัตถุ,4.0
10,6xx2xxx-8,342131,การโต้ตอบระหว่างมนุษย์กับคอมพิวเตอร์,3.0
11,6xx2xxx-8,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,2.5
12,6xx2xxx-8,LI101002,ภาษาอังกฤษ 2,2.5
13,6xx2xxx-8,316201,สถิติขั้นต้น,1.0
14,6xx2xxx-8,342211,ขั้นตอนวิธีและโครงสร้างข้อมูล,2.5
15,6xx2xxx-8,342221,ระบบปฏิบัติการ,1.0
16,6xx2xxx-8,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,3.5
17,6xx2xxx-8,342224,ตรรกะดิจิทัลและระบบฝังตัว,3.5
18,6xx2xxx-8,342431,เทคโนโลยีเว็บ,3.0
19,6xx2xxx-8,LI102003,ภาษาอังกฤษ 3,3.0

In [69]:
course=pd.read_csv('/content/drive/MyDrive/LabDataScince/course.csv')
course.head(15)

   COURSECODE                                         COURSENAME
0      342222                      เครือข่ายคอมพิวเตอร์ขั้นแนะนำ
1      342264                       เทคโนโลยีเคลื่อนที่และไร้สาย
2      342431                                      เทคโนโลยีเว็บ
3      342375               เทคโนโลยีเอ็กซ์เอ็มแอลและการประยุกต์
4      342432                             เทคโนโลยีการออกแบบเว็บ
5      342118                  แนวคิดและการเขียนโปรแกรมเชิงวัตถุ
6    PH511101                                 แนะนําการสาธารณสุข
7      342117  การเขียนโปรแกรมเชิงโครงสร้างสำหรับเทคโนโลยีสาร...
8      342236                      การเขียนโปรแกรมประยุกต์บนเว็บ
9      342267                   การเขียนโปรแกรมอุปกรณ์เคลื่อนที่
10     322462                           การเชื่อมต่ออินเทอร์เน็ต
11     342131               การโต้ตอบระหว่างมนุษย์กับคอมพิวเตอร์
12   AG173372                     การจัดการสัตว์เลี้ยงเป็นเพื่อน
13   TE035013                              การถนอมอาหารเบื้องต้น
14   ED215002                               การถ่ายภาพสร้างสรรค์

In [70]:
course_enroll = pd.merge(course, enroll)
course_enroll

,COURSECODE,COURSENAME,STUDENTCODE,GRADE
0,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,6xx2xxx-8,3.5
1,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,6xx2x278-2,3.5
2,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,6xx2x28x-5,3.5
3,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,6xx2x28x-9,3.0
4,342222,เครือข่ายคอมพิวเตอร์ขั้นแนะนำ,6xx2x291-x,4.0
...,...,...,...,...
2052,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,6xx21249-4,4.0
2053,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,6xx21258-x,3.0
2054,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,6xx21264-8,3.0
2055,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,6xx21265-6,3.5
2056,342162,องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์ขั้นแนะนำ,6xx21x8x-8,1.5

In [80]:
enrolls_matrix = enroll.pivot_table(index=['COURSECODE'],columns=['STUDENTCODE'],values='GRADE').reset_index(drop=True)
enrolls_matrix.fillna( 0, inplace = True )
enrolls_matrix

STUDENTCODE,6xx21249-4,6xx21258-x,6xx21264-8,6xx21265-6,6xx21x81-6,6xx21x87-4,6xx21x8x-2,6xx21x8x-8,6xx21x94-7,6xx2x278-2,...,6xx2xx7-2,6xx2xx8-x,6xx2xx9-8,6xx2xxx-8,6xx2xxx-x,6xx2xxx2-1,6xx2xxx4-7,6xx2xxx5-5,6xx2xxx6-x,6xx2xxx7-1
0,2.0,2.0,2.5,2.5,2.0,2.0,1.5,0.00,2.0,2.5,...,1.0,2.0,1.0,2.5,2.5,2.0,2.5,2.5,1.5,2.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,4.0,...,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,3.5
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.5,2.0,2.5,2.5,2.5,3.5,2.5,0.75,3.0,2.0,...,1.0,2.0,1.0,2.0,2.0,1.0,2.5,2.0,2.0,2.0
4,3.0,3.0,2.5,3.5,3.0,3.5,3.0,1.50,3.0,3.0,...,1.0,2.5,1.5,1.0,3.5,2.0,2.5,2.5,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3.5,...,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.00,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,0.0,2.0,2.5,2.5,0.0,0.0,0.0,0.00,2.5,0.0,...,0.0,0.0,0.0,0.0,2.5,1.5,3.5,3.0,0.0,0.0
65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [81]:
course_similarity=cosine_similarity(enrolls_matrix)
np.fill_diagonal(course_similarity, 0 )
enrolls_matrix = pd.DataFrame( course_similarity )
enrolls_matrix.head(15)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,0.000000,0.551716,0.178104,0.963598,0.956682,0.488115,0.147083,0.967703,0.965102,0.967107,...,0.957039,0.944495,0.958472,0.937559,0.111369,0.377743,0.039375,0.000000,0.636179,0.111369
1,0.551716,0.000000,0.165436,0.536663,0.572512,0.115906,0.000000,0.550692,0.609664,0.597335,...,0.541591,0.535167,0.508186,0.483344,0.000000,0.554556,0.000000,0.000000,0.467443,0.000000
2,0.178104,0.165436,0.000000,0.208044,0.164678,0.046739,0.000000,0.123992,0.158565,0.191303,...,0.120507,0.153038,0.169594,0.126793,0.658505,0.000000,0.000000,0.000000,0.174578,0.658505
3,0.963598,0.536663,0.208044,0.000000,0.970724,0.547354,0.280693,0.970273,0.950292,0.960471,...,0.945692,0.937929,0.951438,0.935315,0.086164,0.334001,0.071082,0.043082,0.650711,0.086164
4,0.956682,0.572512,0.164678,0.970724,0.000000,0.539596,0.242200,0.965922,0.953634,0.961115,...,0.949781,0.941711,0.965018,0.956821,0.050016,0.359482,0.106099,0.075023,0.651662,0.050016
5,0.488115,0.115906,0.046739,0.547354,0.539596,0.000000,0.378077,0.587752,0.498253,0.516118,...,0.500914,0.525279,0.564388,0.526158,0.070977,0.000000,0.200754,0.070977,0.134463,0.070977
6,0.147083,0.000000,0.000000,0.280693,0.242200,0.378077,0.000000,0.227051,0.192055,0.204366,...,0.210952,0.241852,0.238093,0.218199,0.000000,0.000000,0.249029,0.352180,0.000000,0.000000
7,0.967703,0.550692,0.123992,0.970273,0.965922,0.587752,0.227051,0.000000,0.953444,0.954081,...,0.959770,0.944500,0.962411,0.937465,0.057307,0.336297,0.060783,0.000000,0.621479,0.057307
8,0.965102,0.609664,0.158565,0.950292,0.953634,0.498253,0.192055,0.953444,0.000000,0.979643,...,0.958710,0.955636,0.955036,0.922104,0.059491,0.368329,0.098154,0.059491,0.614877,0.059491
9,0.967107,0.597335,0.191303,0.960471,0.961115,0.516118,0.204366,0.954081,0.979643,0.000000,...,0.957026,0.943336,0.957097,0.920335,0.102706,0.354994,0.072624,0.041082,0.618657,0.102706
10,0.973884,0.547979,0.185302,0.965199,0.957833,0.515461,0.185692,0.966909,0.972189,0.970264,...,0.973259,0.963622,0.963369,0.948559,0.099484,0.344929,0.070346,0.000000,0.629251,0.099484
11,0.969701,0.541332,0.193187,0.973206,0.970062,0.550647,0.241080,0.971798,0.976127,0.971073,...,0.961038,0.958711,0.967858,0.949240,0.103717,0.320519,0.117343,0.062230,0.626354,0.103717
12,0.956746,0.567962,0.198134,0.953417,0.954954,0.463913,0.199550,0.940012,0.972427,0.969673,...,0.962888,0.950620,0.953688,0.944603,0.091574,0.343879,0.145693,0.091574,0.631969,0.091574
13,0.972724,0.583229,0.203203,0.961960,0.960008,0.466615,0.163310,0.963387,0.972162,0.962166,...,0.959115,0.945509,0.958937,0.937633,0.093916,0.355204,0.099613,0.070437,0.659937,0.093916
14,0.971604,0.577924,0.133433,0.971462,0.978649,0.522092,0.206540,0.971251,0.964988,0.965596,...,0.963715,0.953454,0.971023,0.955099,0.036370,0.363223,0.077152,0.072739,0.625729,0.036370

In [89]:
try:
    course_inp=input('Enter the reference course title based on which recommendations are to be made: ')
    inp=course[course['COURSENAME']==course_inp].index.tolist()
    inp=inp[0]

    course['similarity'] = enrolls_matrix.iloc[inp]
    course.head(5)

except:
    print("Sorry, the course is not in the database!")

print("Recommended course ",course_inp ,"\n", course.sort_values( ["similarity"], ascending = False )[0:10])

Enter the reference course title based on which recommendations are to be made: การทดสอบซอฟต์แวร์และการประกันคุณภาพ
Recommended course  การทดสอบซอฟต์แวร์และการประกันคุณภาพ
    COURSECODE                                         COURSENAME  similarity
11     342131               การโต้ตอบระหว่างมนุษย์กับคอมพิวเตอร์    0.962837
14   ED215002                               การถ่ายภาพสร้างสรรค์    0.961663
23     870152                               การออกแบบของที่ระลึก    0.960136
18     342266  การพัฒนาโปรแกรมประยุกต์บนเว็บสำหรับอุปกรณ์เคลื่อน    0.959870
20     342372                          การวิเคราะห์และออกแบบระบบ    0.959047
4      342432                             เทคโนโลยีการออกแบบเว็บ    0.958448
3      342375               เทคโนโลยีเอ็กซ์เอ็มแอลและการประยุกต์    0.953210
32     342181                                     ตรรกะและแนวคิด    0.952017
29   PH515330                         ความรอบรู้ด้านสุขภาพทางเพศ    0.952001
9      342267                   การเขียนโปรแกรมอุปกรณ์เคลื่อนที่    0.949808

In [85]:
def get_recommendations(std_id, top_n=10):
    try:
        std_enroll = enroll[enroll['STUDENTCODE'] == std_id]
        if std_enroll.empty:
          return "User not found in the dataset."
        std_course_ids = std_enroll['COURSECODE'].unique()
        # Calculate average similarity for movies the user has rat๐ed
        similarities = []
        for course_id in std_course_ids:
            course_index = course[course['COURSECODE'] == course_id].index[0]  # Get the index
            similarities.append(enrolls_matrix.iloc[course_index])

        average_similarity = pd.concat(similarities, axis=1).mean(axis=1)

        # Sort movies based on average similarity and recommend top_n movies
        course['similarity'] = average_similarity
        recommendations = course.sort_values(by=['similarity'], ascending=False)
        return recommendations.head(top_n)

    except Exception as e:
        return f"An error occurred: {e}"

# Get recommendations for a specific user
std_id_input = input("Enter the student ID: ")
recommendations = get_recommendations(std_id_input)
recommendations

Enter the student ID: 6xx2x28x-9

   COURSECODE                                      COURSENAME  similarity
50     419130                                     วัฒนธรรมไทย    0.649375
31   FA301203                                   ดนตรีสมัยนิยม    0.648172
49     342281                           ระบบสารสนเทศทางธุรกิจ    0.643689
13   TE035013                           การถนอมอาหารเบื้องต้น    0.643533
10     322462                        การเชื่อมต่ออินเทอร์เน็ต    0.642553
58     854163                          ศิลปะภาพพิมพ์ตะแกรงไหม    0.640049
23     870152                            การออกแบบของที่ระลึก    0.637352
16     342475                               การทำเหมืองข้อมูล    0.635705
57     853161  ศิลปหัตถกรรมเครื่องเคลือบดินเผาเพื่อการพาณิชย์    0.634765
29   PH515330                      ความรอบรู้ด้านสุขภาพทางเพศ    0.633326

std_id_input = int(input("Enter the student ID: "))
recommendations = get_recommendations(std_id_input)
recommendations